AllCops:
  Exclude:
    - 'bin/*'
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'
    - 'db/migrate/20190822152152_create_event_store_events.rb'
    - 'db/migrate/20190904215200_create_workout_set.rb'
    - 'db/migrate/20191117114210_devise_create_users.rb'
    
Layout/ArgumentAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolProc:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false